# Generated by Django 5.0.4 on 2024-04-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_Name', models.FloatField(max_length=20)),
                ('Year', models.FloatField(max_length=20)),
                ('Present_Price', models.FloatField(max_length=20)),
                ('Kms_Driven', models.FloatField(max_length=20)),
                ('Fuel_Type', models.FloatField(max_length=20)),
                ('Seller_Type', models.FloatField(max_length=20)),
                ('Transmission', models.FloatField(max_length=20)),
            ],
        ),
    ]
